In [1]:
import numpy as np
import pickle

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, f1_score

In [4]:
X_test = np.load('Data/X_test.npy')
y_test = np.load('Data/y_test.npy')

In [2]:
with open("Trained_models/Random_Forest.pkl", "rb") as f:
    rf = pickle.load(f)
with open("Trained_models/KNN.pkl", "rb") as f:
    knn = pickle.load(f)
with open("Trained_models/SVM.pkl", "rb") as f:
    svm = pickle.load(f)

models=[
    (rf, 0.45),
    (knn, 0.35),
    (svm, 0.2)
]

In [7]:
n_models = len(models)

ensem_pred = np.zeros_like(y_test, dtype=np.float64)

for model, w in models:
    pred = model.predict(X_test)
    ensem_pred += pred * w
    print(pred)

[ 0  0  1 ... -2 -1  0]
[ 0  0  1 ... -1  0  0]
[-1  0  1 ... -2 -1  0]


In [8]:
ensem_pred = np.round(ensem_pred)
print(classification_report(y_test, ensem_pred))

              precision    recall  f1-score   support

          -2       0.52      0.71      0.60       473
          -1       0.65      0.71      0.68      2746
           0       0.79      0.69      0.74      4174
           1       0.50      0.61      0.55       522
           2       0.61      0.51      0.56       105

    accuracy                           0.69      8020
   macro avg       0.62      0.65      0.63      8020
weighted avg       0.71      0.69      0.70      8020

